ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.error-strings]

[rule.receiver-naming]

[rule.time-naming]

[rule.var-naming]
arguments = [["API", "CI", "FIFO", "HTTP", "HTTPS", "ID", "JSON", "URL"], [], [{ upper-case-const = true }]]
